In [1]:
import matplotlib.pyplot as plt
import pandas as pd
import pylab as pl
import numpy as np
%matplotlib inline
import seaborn as sns

In [28]:
file = "https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-ML0101EN-SkillsNetwork/labs/FinalModule_Coursera/data/loan_train.csv"


In [29]:
df = pd.read_csv(file)

In [30]:
df.head()

Unnamed: 0.1  Unnamed: 0 loan_status  Principal  terms effective_date  \
0             0           0     PAIDOFF       1000     30       9/8/2016   
1             2           2     PAIDOFF       1000     30       9/8/2016   
2             3           3     PAIDOFF       1000     15       9/8/2016   
3             4           4     PAIDOFF       1000     30       9/9/2016   
4             6           6     PAIDOFF       1000     30       9/9/2016   

    due_date  age             education  Gender  
0  10/7/2016   45  High School or Below    male  
1  10/7/2016   33              Bechalor  female  
2  9/22/2016   27               college    male  
3  10/8/2016   28               college  female  
4  10/8/2016   29               college    male

In [31]:
a = df["education"].value_counts()
a


High School or Below    151
college                 149
Bechalor                 44
Master or Above           2
Name: education, dtype: int64

In [36]:
X = df[["Principal","terms","age","education","Gender"]].values
X[0:5]

array([[1000, 30, 45, 'High School or Below', 'male'],
       [1000, 30, 33, 'Bechalor', 'female'],
       [1000, 15, 27, 'college', 'male'],
       [1000, 30, 28, 'college', 'female'],
       [1000, 30, 29, 'college', 'male']], dtype=object)

**now e will make the dummy values**

In [37]:
from sklearn import preprocessing
eductaion = preprocessing.LabelEncoder()
eductaion.fit(['High School or Below','college','Bechalor','Master or Above'])
X[:,3] = eductaion.transform(X[:,3]) 
gender = preprocessing.LabelEncoder()
gender.fit([ 'male', 'female'])
X[:,4] = gender.transform(X[:,4])




In [38]:
X[0:5]

array([[1000, 30, 45, 1, 1],
       [1000, 30, 33, 0, 0],
       [1000, 15, 27, 3, 1],
       [1000, 30, 28, 3, 0],
       [1000, 30, 29, 3, 1]], dtype=object)

In [40]:
y = df["loan_status"]

In [42]:
y[0:5].values

array(['PAIDOFF', 'PAIDOFF', 'PAIDOFF', 'PAIDOFF', 'PAIDOFF'],
      dtype=object)

**now normalize the data set**

In [43]:
from sklearn import preprocessing


In [44]:
X = preprocessing.StandardScaler().fit(X).transform(X.astype(float))


In [45]:
X[0:5]

array([[ 0.51578458,  0.92071769,  2.33152555, -0.64691859,  0.42056004],
       [ 0.51578458,  0.92071769,  0.34170148, -1.5212695 , -2.37778177],
       [ 0.51578458, -0.95911111, -0.65321055,  1.10178323,  0.42056004],
       [ 0.51578458,  0.92071769, -0.48739188,  1.10178323, -2.37778177],
       [ 0.51578458,  0.92071769, -0.3215732 ,  1.10178323,  0.42056004]])

**now splitting the data**

In [46]:
from sklearn.model_selection import train_test_split

In [47]:
X_train,x_test,y_train,y_test = train_test_split(X,y,test_size = 0.2,random_state = 4)

In [48]:
X_train.shape,x_test.shape,y_train.shape,y_test.shape

((276, 5), (70, 5), (276,), (70,))

# KNN Neighbours

In [93]:
from sklearn.neighbors import KNeighborsClassifier

In [94]:
k = 4
neigh = KNeighborsClassifier(n_neighbors=k).fit(X_train,y_train)

In [95]:
neigh

KNeighborsClassifier(n_neighbors=4)

In [99]:
yknn = neigh.predict(x_test)

In [100]:
yknn[0:5]

array(['PAIDOFF', 'COLLECTION', 'PAIDOFF', 'COLLECTION', 'PAIDOFF'],
      dtype=object)

In [102]:
y_test[0:5]

63     PAIDOFF
34     PAIDOFF
186    PAIDOFF
146    PAIDOFF
130    PAIDOFF
Name: loan_status, dtype: object

**now check the accuracy of the model**

In [103]:
from sklearn.metrics import classification_report, confusion_matrix
import itertools

In [104]:
print (classification_report(y_test, yknn))

              precision    recall  f1-score   support

  COLLECTION       0.23      0.33      0.27        15
     PAIDOFF       0.79      0.69      0.74        55

    accuracy                           0.61        70
   macro avg       0.51      0.51      0.50        70
weighted avg       0.67      0.61      0.64        70



In [105]:
from sklearn import metrics


In [106]:
metrics.accuracy_score(y_test,yknn)

0.6142857142857143

# decision tree classfication

In [59]:
from sklearn.tree import DecisionTreeClassifier
import sklearn.tree as tree

In [60]:
drugTree = DecisionTreeClassifier(criterion="entropy", max_depth = 4)

drugTree 

DecisionTreeClassifier(criterion='entropy', max_depth=4)

In [63]:
drugTree.fit(X_train,y_train)

DecisionTreeClassifier(criterion='entropy', max_depth=4)

In [64]:
drugpred = drugTree.predict(x_test)

In [65]:
drugpred[0:5]

array(['PAIDOFF', 'PAIDOFF', 'PAIDOFF', 'PAIDOFF', 'PAIDOFF'],
      dtype=object)

In [66]:
y_test[0:5]

63     PAIDOFF
34     PAIDOFF
186    PAIDOFF
146    PAIDOFF
130    PAIDOFF
Name: loan_status, dtype: object

**now for accuracy**

In [67]:
print (classification_report(y_test,drugpred))

              precision    recall  f1-score   support

  COLLECTION       0.00      0.00      0.00        15
     PAIDOFF       0.79      1.00      0.88        55

    accuracy                           0.79        70
   macro avg       0.39      0.50      0.44        70
weighted avg       0.62      0.79      0.69        70



C:\Users\ahsan\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\ahsan\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\ahsan\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [107]:
metrics.accuracy_score(y_test,drugpred)

0.7857142857142857

# Logistic Regression with Python


In [108]:
from sklearn.linear_model import LogisticRegression

In [109]:
LR = LogisticRegression(C=0.01, solver='liblinear').fit(X_train,y_train)
LR

LogisticRegression(C=0.01, solver='liblinear')

In [115]:
ylr = LR.predict(x_test)
ylr[0:5]

array(['PAIDOFF', 'PAIDOFF', 'PAIDOFF', 'PAIDOFF', 'PAIDOFF'],
      dtype=object)

In [111]:
y_test[0:5]

63     PAIDOFF
34     PAIDOFF
186    PAIDOFF
146    PAIDOFF
130    PAIDOFF
Name: loan_status, dtype: object

In [112]:
yhat_prob = LR.predict_proba(x_test)
yhat_prob[0:5]

array([[0.43312501, 0.56687499],
       [0.38304069, 0.61695931],
       [0.39785039, 0.60214961],
       [0.44899743, 0.55100257],
       [0.42385469, 0.57614531]])

<h2 id="evaluation">Evaluation</h2>

In [116]:
print (classification_report(y_test, ylr))

              precision    recall  f1-score   support

  COLLECTION       0.00      0.00      0.00        15
     PAIDOFF       0.79      1.00      0.88        55

    accuracy                           0.79        70
   macro avg       0.39      0.50      0.44        70
weighted avg       0.62      0.79      0.69        70



C:\Users\ahsan\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\ahsan\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\ahsan\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [117]:
metrics.accuracy_score(y_test,ylr)

0.7857142857142857

# support vector machine(svm)

In [118]:
from sklearn import svm
clf = svm.SVC(kernel='rbf')
clf.fit(X_train, y_train) 

SVC()

In [119]:
ysvm = clf.predict(x_test)

In [120]:
ysvm[0:5],y_test[0:5]

(array(['PAIDOFF', 'PAIDOFF', 'PAIDOFF', 'PAIDOFF', 'PAIDOFF'],
       dtype=object),
 63     PAIDOFF
 34     PAIDOFF
 186    PAIDOFF
 146    PAIDOFF
 130    PAIDOFF
 Name: loan_status, dtype: object)

In [121]:
from sklearn.metrics import f1_score
f1_score(y_test, yhat, average='weighted') 

0.6914285714285714

In [122]:
print (classification_report(y_test, ysvm))

              precision    recall  f1-score   support

  COLLECTION       0.00      0.00      0.00        15
     PAIDOFF       0.79      1.00      0.88        55

    accuracy                           0.79        70
   macro avg       0.39      0.50      0.44        70
weighted avg       0.62      0.79      0.69        70



C:\Users\ahsan\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\ahsan\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\ahsan\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [123]:
metrics.accuracy_score(y_test,ysvm)

0.7857142857142857

## Note: as we can see from the accuracy except KNN neighbours all the classification techniques like Decision tree classification, Logistic Regression and Support vector machine are the best classifier.